apiVersion: apps/v1
kind: Deployment
metadata:
  name: faer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faer
  template:
    metadata:
      labels:
        app: faer
    spec:
      containers:
      - image: okteto.dev/faer:latest
        name: faer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "11716002-1381-4ba0-bd04-4f9c111dac63"
        - name: Vless_Path
          value: "/fgf34gfhj5jyu"
        - name: Vmess_UUID
          value: "11716002-1381-4ba0-bd04-4f9c111dac63"
        - name: Vmess_Path
          value: "/fdsdeo87dsa6ehtd"
        - name: Share_Path
          value: "/v2link"
